sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - python3.5
            - python3.5-dev
            - python-pip
            - python-virtualenv
            # Needed for ARM gcc
            - libbz2-1.0:i386
            - libncurses5:i386

language: cpp

matrix:
    include:
        - compiler: clang
          env: BUILD_TYPE="tests"
        - compiler: gcc
          env: BUILD_TYPE="tests"
        - compiler: clang
          env: BUILD_TYPE="client-tests"

install:
    - ci/install.sh

script:
    - ci/build.sh


